// frontend/src/components/Header.vue
<template>
  <header class="bg-neutral-900 border-b border-neutral-700 p-4">
    <div class="max-w-4xl mx-auto flex items-center">
      <div class="flex-1 flex items-center">
        <button 
          v-if="isAuthenticated"
          @click="goHome"
          class="text-white hover:text-neutral-300 transition-colors"
        >
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
        </button>
      </div>
      
      <h1 class="text-xl font-semibold text-white">Prompt Optimizer</h1>

      <div class="flex-1 flex items-center justify-end space-x-3">
        <template v-if="isAuthenticated">
          <button
            @click="goHistory"
            class="bg-white hover:bg-gray-100 text-black px-4 py-2 rounded transition-colors"
          >
            History
          </button>
          <button 
            @click="logout"
            class="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded transition-colors"
          >
            Logout
          </button>
        </template>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import { computed } from 'vue';

const router = useRouter();

const isAuthenticated = computed(() => {
  const token = localStorage.getItem('token');
  const isExpired = token ? new Date().getTime() > JSON.parse(atob(token.split('.')[1])).exp * 1000 : false;
  return token !== null && !isExpired;
});

const goHome = () => {
  router.push('/');
};

const logout = () => {
  localStorage.removeItem('token');
  router.push('/login');
};

const goHistory = () => {
    router.push("/history")
}
</script>

// frontendv2/components/Header.jsx
"use client"

import React from 'react';
import { useRouter } from 'next/navigation';
import { LogOut, User, History, Sparkles, Menu } from 'lucide-react';

export default function Header() {
  const router = useRouter();

  const handleLogout = () => {
    localStorage.removeItem('token');
    router.push('/login');
  };

  const navigateTo = (path) => {
    router.push(path);
  };

  return (
    <header className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border-b border-gray-200 dark:border-gray-700 sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center">
            <div className="flex-shrink-0 flex items-center">
              <div className="w-8 h-8 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-lg flex items-center justify-center mr-3">
                <Sparkles className="w-5 h-5 text-white" />
              </div>
              <span className="text-xl font-bold text-gray-900 dark:text-gray-100">
                Prompt Optimizer
              </span>
            </div>
          </div>

          <nav className="hidden md:flex space-x-8">
            <button
              onClick={() => navigateTo('/dashboard')}
              className="flex items-center px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors duration-200"
            >
              <Sparkles className="w-4 h-4 mr-2" />
              Dashboard
            </button>
            <button
              onClick={() => navigateTo('/history')}
              className="flex items-center px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors duration-200"
            >
              <History className="w-4 h-4 mr-2" />
              History
            </button>
          </nav>

          <div className="flex items-center space-x-4">
            <div className="hidden md:flex items-center space-x-3">
              <div className="w-8 h-8 bg-gray-200 dark:bg-gray-600 rounded-full flex items-center justify-center">
                <User className="w-4 h-4 text-gray-600 dark:text-gray-300" />
              </div>
            </div>
            
            <button
              onClick={handleLogout}
              className="flex items-center px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-red-600 dark:hover:text-red-400 transition-colors duration-200"
            >
              <LogOut className="w-4 h-4 mr-2" />
              <span className="hidden sm:inline">Logout</span>
            </button>
          </div>
        </div>
      </div>
    </header>
  );
}
